-- Add new RoleType enum values
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'PROPRIETAIRE';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'DAF';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'COMPTABLE_EXTERNE';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'RESPONSABLE_RECOUVREMENT';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'CAISSIER';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'COMMERCIAL_PROPRE';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'ASSISTANT';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'ASSOCIE';

-- Add permissionsRetirees column
ALTER TABLE "utilisateurs" ADD COLUMN IF NOT EXISTS "permissionsRetirees" TEXT[] NOT NULL DEFAULT '{}';
